# Generated by Django 2.0.3 on 2018-10-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0002_auto_20181008_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_no',
            field=models.SmallIntegerField(null=True),
        ),
    ]
