# Generated by Django 2.0.3 on 2018-10-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0003_auto_20181010_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_no',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_no',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='address',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressBook.Person'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='address',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'prywatny'), (2, 'domowy'), (3, 'służbowy'), (4, 'secret')], default=1),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressBook.Person'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'prywatny'), (2, 'domowy'), (3, 'służbowy'), (4, 'secret')], default=1),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressBook.Person'),
        ),
    ]
